<?php

namespace Nemundo\Core\Command;

use Nemundo\Core\Debug\Debug;

class LocalCommand extends AbstractLocalCommand  // AbstractCommand
{

    /**
     * @var bool
     */
    //public $showOutput = false;

   /* public function runCommand()
    {

        //$this->loadCommand();
        //$newCommand = join(' && ', $this->commandList);
        $newCommand=$this->getChainedCommand();

        exec($newCommand, $output);


        //(new Debug())->write($newCommand);

        if ($this->showOutput) {
            (new Debug())->write($output);
        }

        return $output;

    }*/


    public function runCommand()
    {
        return parent::runCommand(); // TODO: Change the autogenerated stub
    }

}