<?php

namespace Nemundo\Core\Http\Parameter;


use Nemundo\Core\Base\DataSource\AbstractDataSource;


// GetParameterReader

class UrlParameterReader extends AbstractDataSource
{


    protected function loadData()
    {

    }


    /**
     * @return GetParameter[]
     */
    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }


}