<?php

namespace Nemundo\Core\Type\Geo;

use Nemundo\Core\Base\AbstractBaseClass;

class GeoCoordinate extends AbstractGeoCoordinate
{

    protected function loadGeoCoordinate()
    {
        // TODO: Implement loadGeoCoordinate() method.
    }


    public function fromText($text)
    {
        return parent::fromText($text); // TODO: Change the autogenerated stub
    }


    // isNull Function ???

    /**
     * @var float
     */
    //public $latitude;  // = 0;

    /**
     * @var float
     */
    /*public $longitude;  // = 0;


    public function fromString()
    {

// 47.200985, 8.464844

    }

    public function getText()
    {
        $text = $this->latitude . ',' . $this->longitude;
        return $text;
    }*/

}